# Generated by Django 4.2.7 on 2025-03-10 09:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookArrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='book_arrival_images/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Поступление книги',
                'verbose_name_plural': 'Поступления книг',
            },
        ),
        migrations.CreateModel(
            name='MediaCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('coverage_period', models.CharField(max_length=255, verbose_name='Период охвата')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='media_coverage_images/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Освещение в СМИ',
                'verbose_name_plural': 'Освещения в СМИ',
            },
        ),
        migrations.CreateModel(
            name='NewsDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='news_detail_images/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Подробности новости',
                'verbose_name_plural': 'Подробности новостей',
            },
        ),
    ]
